/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("application")
    id("org.openjfx.javafxplugin") version "0.0.14"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.guava)
    implementation("org.openjfx:javafx-controls:21.0.8")
    implementation("org.openjfx:javafx-fxml:21.0.8")

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass.set("it.unicam.cs.mpgc.jbudget126603.view.MainApp")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

javafx {
    version = "21.0.8"
    modules("javafx.controls", "javafx.fxml")
}
